type: object
requires: ["matrix_homeserver", "matrix_user_domain", "username_template"]
properties:
  matrix_homeserver:
    type: string
  matrix_user_domain:
    type: string
  username_template:
    type: string
  matrix_admin_room:
    type: string
  enable_metrics:
    type: boolean
